config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  root 'pages#accueil'

  get '/accueil' => 'pages#accueil'
  get '/proposer'  => 'groupes#new'
  get '/mes_projets'  => 'groupes#index_mygroups'
  get '/voter' => 'groupes#index'
  get '/resultats' => 'groupes#index_outdated'
  get '/liste_utilisateurs' => 'utilisateurs#index'
  get '/a_propos' => 'pages#a_propos'

  resources :utilisateurs
  resources :delegations
  resources :sessions
  resources :groupes
  resources :lieux
  resources :categories
  resources :sujets do
    resources :commentaires
  end

  get '/ammendements/:id/new' => 'sujets#nouvel_ammendement', as: :nouvel_ammendement
  post '/ammendements' => 'sujets#creer_ammendement', as: :creer_ammendement

  patch '/sujets/:id/incremente_votes_pour' => 'sujets#incremente_votes_pour', as: :incremente_votes_pour
  patch '/sujets/:id/incremente_votes_contre' => 'sujets#incremente_votes_contre', as: :incremente_votes_contre
  patch '/sujets/:id/incremente_votes_blancs' => 'sujets#incremente_votes_blancs', as: :increase_votes_blancs

  get '/envoi_vote/:sujet/:vote' => 'sujets#envoi_vote'

  get 'sessions/new'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'utilisateurs#new', :as => 'sign_up'

  get 'groupes/:id/graphe' => 'groupes#graphe', :as => 'graphe'

  get 'admin' => 'admin#index'

  get '/accept/:id/:cle' => 'utilisateurs#verifier_mairie', as: :verifier_mairie

end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base
  belongs_to :lieu

  has_many :delegations_recues,
           class_name: 'Delegation',
           foreign_key: 'receveur_id'
  has_many :delegations_donnees,
           class_name: 'Delegation',
           foreign_key: 'donneur_id'
  has_many :delegations_accumulees,
           class_name: 'Delegation',
           foreign_key: 'rec_racine_id'
  has_many :categories_recues,
           class_name: 'Categorie',
           :through => :delegations_recues
  has_many :categories_donnees,
           class_name: 'Categorie',
           :through => :delegations_donnees

  has_many :sujets_crees,
      class_name: 'Sujet'

  has_and_belongs_to_many :sujets,
                          class_name: 'Sujet',
                          join_table: 'votes'

  has_many :commentaires

  #validates :nom, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :mail, presence: true,
                   length: { maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }

  has_secure_password
  validates_presence_of :password, on: :create
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true # allow_blank pour autoriser la mise à jour (voir Aurélien pour plus d'infos, c'est une maxi magouille)

  # Image de profil
  mount_uploader :image, ImageUploader
  validate :taille_image

  validates_presence_of :nom, :prenom

  before_save {
    self.mail = mail.downcase
    :encrypt_password
  }

  def self.search(search)
    where('nom LIKE :s or prenom LIKE :s or mail LIKE :s', s: search)
  end

  def civilite_texte
    UtilisateursHelper.civilites[civilite]
  end

  def nom_complet
    [prenom.to_s, nom.upcase.to_s].delete_if{ |s| s.empty? }.join(' ')
  end

  def admin?
    UtilisateursHelper.droits_egal?(:admin, droits)
  end

  def pelo?
    UtilisateursHelper.droits_egal?(:pelo, droits)
  end

  # Est-ce que l'utisateur a donné son vote pour la +categorie+
  def delegation_donnee?(categorie_id)
    self.delegations_donnees.exists?(categorie_id: categorie_id)
  end

  # Nombre de votes possédés par l'utilisateur pour la +catégorie+
  def votes_disponibles(categorie_id)
    if delegation_donnee? categorie_id
      # Il a donné une délégation : il n'a plus de vote
      0
    else
      # Sinon, c'est le nombre de délégations avec la racine == self + 1 (le sien)
      delegations_accumulees.where(categorie_id: categorie_id).count + 1
    end
  end

  # Les utilisateurs qui ont donné leur vote (directement ou pas) à +self+
  def delegueurs(categorie_id)
    if delegation_donnee? categorie_id
      Utilisateur.none
    else
      Utilisateur.where(id: delegations_accumulees
                                .where(categorie_id: categorie_id).pluck(:donneur_id))
    end
  end

  def tous_delegueurs
    delegations_recues.collect{|d| {donneur: d.donneur, categorie: d.categorie}}
  end

  def tous_delegues
    delegations_donnees.collect{|d| {receveur: d.receveur, categorie: d.categorie}}
  end


  def generer_cle
    # génération de clé pour vérifier les utilisateurs par la mairie.
    # TODO : A remplacer par un vrai truc sécurisé ? mieux que log...
    cle = (Math.log(self.id)+4)*10000000000
    cle.to_i
  end

  def en_attente?
    UtilisateursHelper.droits_egal?(:en_attente, droits)
  end

  def delegueurs_et_moi(categorie_id)
    [self] + self.delegueurs(categorie_id)
  end

  private
    def taille_image
      if image.size > 5.megabytes
        errors.add(:image, 'ne doit pas exéder 5Mo')
      end
    end

end

app/controllers/utilisateurs_controller.rb
# coding: utf-8
class UtilisateursController < ApplicationController

  def index
    @utilisateurs = Utilisateur.all
    if params[:search]
      @utilisateurs = Utilisateur.search(params[:search]).order('created_at DESC')
    else
      @utilisateurs = Utilisateur.order('created_at DESC')
    end
  end

  def show
    @utilisateur = Utilisateur.find_by_id(params[:id])
  end

  def new
    @utilisateur = Utilisateur.new
  end

  def edit
    @utilisateur = Utilisateur.find_by_id(params[:id])

    if !utilisateur_courant_ou_admin?(@utilisateur)
      forbidden
    end
  end

  def create
    @utilisateur = Utilisateur.new(utilisateur_params)

    # Si production : On envoie le mail à la mairie, on attend le retour, etc.
    # Si développement : On inscrit le pélo automatiquement
    if Rails.env == 'development'
      @utilisateur.droits = UtilisateursHelper.droits[:en_attente]
    elsif Rails.env == 'production'
      @utilisateur.droits = Utilisateur.any? ? UtilisateursHelper.droits[:pelo] : UtilisateursHelper.droits[:admin]
    end

    if @utilisateur.save

      # Si production : email de bienvenue
      if Rails.env == 'development'
        UtilisateurMailer.welcome_email(@utilisateur).deliver_now
        UtilisateurMailer.verif_mairie(@utilisateur).deliver_now
      end

      # log_in @utilisateur # Connexion automatique à l'inscription
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @utilisateur = Utilisateur.find_by_id(params[:id])

    # Interdit si l'utilisateur essaye de mettre à jour des droits sans être administrateur...
    if params.include? :droits && !utilisateur_courant.admin?
      forbidden
    end

    lieu = Lieu.find_by_id(params[:utilisateur][:lieu_id])
    @utilisateur.lieu = lieu

    if @utilisateur.update(utilisateur_params)
      redirect_to @utilisateur
    else
      render 'edit'
    end
  end

  def verifier_mairie
    @utilisateur = Utilisateur.find_by_id(params[:id])
    if params[:cle].to_i == @utilisateur.generer_cle

      # Le premier utilisateur créé est administrateur
      #@utilisateur.droits = Utilisateur.any? ? UtilisateursHelper.droits[:pelo] : UtilisateursHelper.droits[:admin]
      Utilisateur.update(@utilisateur.id, droits: Utilisateur.any? ? UtilisateursHelper.droits[:pelo] : UtilisateursHelper.droits[:admin])
      UtilisateurMailer.verif_mairie_reussie(@utilisateur).deliver_now
    else
      forbidden
    end
  end

  private
    def utilisateur_params
      params.require(:utilisateur).permit(
        :civilite,
        :prenom,
        :nom,
        :date_de_naissance,
        :mail,
        :lieu,
        :image,
        :password,
        :password_confirmation,
        :droits
      )
    end
end

app/helpers/utilisateurs_helper.rb
# coding: utf-8
module UtilisateursHelper

  def self.droits
    {
      :pelo => 0, # pélo = citoyen normal
      :elu => 1,
      :admin => 2,
      :en_attente => 3
    }
  end

  def self.droits_egal?(cible, droit)
    droits[cible] == droit
  end

  def self.droits_select
    # Convertit la liste de droits dans la format [[:pelo, 0], ...]
    # Utilisé pour les <select>
    droits.to_a
  end

  def self.civilites
    {
      0 => '',
      1 => 'M.',
      2 => 'Mme'
    }
  end

  def self.civilites_select
    # Convertit la liste de civilités dans le format [["", 0], ...].
    # Utilisé pour les <select>
    civilites.to_a.collect { |l| l.reverse }
  end

end

app/views/utilisateurs/edit.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h2>Modification du profil</h2>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">

    <%= form_for(@utilisateur, html: { multipart: true }) do |f| %>

      <%= render 'layouts/erreurs', erreurs: @utilisateur.errors %>

      <div class="form-group">
        <%= f.label :lieu_id, 'Lieu de résidence' %>
        <%= f.select :lieu_id, LieuxHelper.lieux_select, { include_blank: true }, { class: 'form-control' } %>
      </div>

      <div class="form-group">
        <%= f.label :image, 'Image de profil' %>
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
        <p class="help-block">
          L'image ne doit pas dépasser 5Mo et sera redimensionnée en 200x200 pixels.
        </p>
      </div>

      <% if utilisateur_courant.admin? %>
        <div class="form-group">
          <%= f.label :droits %>
          <%= f.select :droits, UtilisateursHelper.droits_select, { include_blank: true }, { class: "form-control" } %>
        </div>
      <% end %>

      <%= link_to 'Retour', utilisateur_path(utilisateur_courant), class: 'btn btn-default' %>

      <%= f.submit 'Mettre à jour', class: 'btn btn-primary' %>

    <% end %>

  </div>
</div>

app/views/utilisateurs/index.html.erb
<div class="row">
  <div class="text-center col-lg-12">
    <h1>Liste d'utilisateurs</h1>
  </div>
</div>

<div class="row">
  <div class="text-center col-lg-12">
    <%= form_tag(liste_utilisateurs_path, :method => 'get', id: 'search-form', class: 'form-inline') do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Rechercher utilisateur', class: 'form-control' %>
      <%= submit_tag "Rechercher", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">

    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Adresse</th>
          <th>Rôle</th>
        </tr>
      </thead>
      <tbody>
      <%==  %>
        <% @utilisateurs.each do |utilisateur| %>
          <tr onclick="location.href='<%= utilisateur_path utilisateur %>';">
            <td>
              <% if utilisateur.image? %>
                <%= image_tag(utilisateur.image.url, size: '32', class: 'img-responsive center-block img-circle') %>
              <% end %>
            </td>
            <td><%= utilisateur.nom %></td>
            <td><%= utilisateur.prenom %></td>
            <td><%= utilisateur.mail %></td>

            <% if utilisateur.admin? %>
              <td><%= 'Administrateur' %></td>

            <% elsif utilisateur.pelo? %>
              <td><%= 'Citoyen' %></td>

            <%else%>
              <td><%= 'Élu' %></td>

            <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/utilisateurs/new.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Créer un compte</h1>
  </div>
</div>

<%= form_for @utilisateur do |f| %>

    <%= render 'layouts/erreurs', erreurs: @utilisateur.errors %>

    <div class="form-group">
      <%= f.label :civilite %>
      <%= f.select :civilite, UtilisateursHelper.civilites_select, {}, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :prenom, 'Prénom' %>
      <%= f.text_field :prenom, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :nom, 'Nom' %>
      <%= f.text_field :nom, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :date_de_naissance %><br>
      <%= f.date_select :date_de_naissance,
        use_two_digit_numbers: true,
        date_separator: " / ",
        start_year: Date.today.year - 120,
        end_year: Date.today.year,
        include_blank: true
      %>
    </div>

    <div class="form-group">
      <%= f.label :lieu_de_naissance, "Lieu de naissance" %><br>
      <%= f.text_field :lieu_de_naissance, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :lieu_id , "Lieu de résidence" %><br>
      <%= f.select :lieu_id, LieuxHelper.lieux_select, { include_blank: true }, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :mail, 'Courriel' %><br>
      <%= f.text_field :mail, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Mot de passe' %><br>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirmer le mot de passe' %><br>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :fichier, 'Pièce d\'identité' %>
      <%= f.file_field :fichier %>
      <p class="help-block">
        Afin de valider votre inscription auprès de votre mairie, merci de joindre une copie de pièce d'identité valide.
      </p>
    </div>

    <%= f.submit 'Créer un compte', class: 'btn btn-primary btn-lg' %>

    <%= link_to 'J\'ai déjà un compte', log_in_path, class: 'btn btn-default btn-lg' %>

<% end %>

app/views/utilisateurs/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2 class="text-center">Profil d'utilisateur</h2>
  </div>
</div>

<div class="row">

  <div class="col-md-4">
    <% if @utilisateur.image? %>
      <%= image_tag(@utilisateur.image.url, class: 'img-responsive center-block img-circle') %>
    <% else %>
      <%= image_tag('fraaaanz.png', class: 'img-responsive center-block') %>
    <% end %>
  </div>

  <div class="col-md-4">

    <h2>
      <%= @utilisateur.nom_complet %>
      <% if @utilisateur.admin? %>
        <small class="text-uppercase">Administrateur</small>
      <% end %>
    </h2>

    <dl>

      <% unless @utilisateur.date_de_naissance.nil? %>
        <dt>Date de naissance</dt>
        <dd><%= l @utilisateur.date_de_naissance, format: :long %></dd>
      <% end %>

      <% unless @utilisateur.lieu.nil? %>
        <dt>Lieu de résidence</dt>
        <dd><%= @utilisateur.lieu.nom %></dd>
      <% end %>
    </dl>


    <% if utilisateur_courant_ou_admin?(@utilisateur) %>
      <%= link_to 'Modifier le profil', edit_utilisateur_path(@utilisateur), class: 'btn btn-default btn-lg' %>
    <% end %>

  </div>

  <div class='col-md-4'>


    <%= link_to 'Créer une délégation', new_delegation_path(receveur_id: @utilisateur.id),
                class: 'btn btn-default btn-lg' %>

    <% if utilisateur_courant?(@utilisateur) %>
      <p>Je délègue à d'autres citoyens :</p>
          <table class="table table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Délégué</th>
                <th>Catégorie</th>
              </tr>
            </thead>
            <tbody>
              <% @utilisateur.delegations_donnees.each do |d| %>
                <tr onclick="location.href='<%= utilisateur_path(d.receveur) %>';">
                  <td>
                    <% unless d.receveur.image.url.nil? %>
                        <%= image_tag(d.receveur.image.url, size: '32', class: 'img-responsive center-block img-circle') %>
                    <% end %>
                  </td>
                  <td><%= d.receveur.nom_complet %></td>
                  <td><%= d.categorie.nom %></td>
                  <td><%= link_to 'Supprimer', {controller: :delegations, action: :destroy, id: d.id},
                                    method: :delete, class: 'btn btn-default' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

      <p>D'autres citoyens me délèguent :</p>
          <table class="table table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Délégueur</th>
                <th>Catégorie</th>
              </tr>
            </thead>
            <tbody>
              <% @utilisateur.delegations_recues.each do |d| %>
                <tr onclick="location.href='<%= utilisateur_path(d.donneur) %>';">
                  <td>
                    <% unless d.donneur.image.url.nil? %>
                        <%= image_tag(d.donneur.image.url, size: '32', class: 'img-responsive center-block img-circle') %>
                    <% end %>
                  </td>
                  <td><%= d.donneur.nom_complet %></td>
                  <td><%= d.categorie.nom %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
    <% end %>

  </div>



</div>

app/views/utilisateurs/verifier_mairie.html.erb
<p>
  L'inscription de l'utilisateur <%= @utilisateur.nom_complet %> a bien été prise en compte.
  Celui-ci a reçu un email de confirmation d'inscription.
</p>