config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  root 'pages#accueil'

  get '/accueil' => 'pages#accueil'
  get '/proposer'  => 'groupes#new'
  get '/mes_projets'  => 'groupes#index_mygroups'
  get '/voter' => 'groupes#index'
  get '/resultats' => 'groupes#index_outdated'
  get '/liste_utilisateurs' => 'utilisateurs#index'
  get '/a_propos' => 'pages#a_propos'

  resources :utilisateurs
  resources :delegations
  resources :sessions
  resources :groupes
  resources :lieux
  resources :categories
  resources :sujets do
    resources :commentaires
  end

  get '/ammendements/:id/new' => 'sujets#nouvel_ammendement', as: :nouvel_ammendement
  post '/ammendements' => 'sujets#creer_ammendement', as: :creer_ammendement

  patch '/sujets/:id/incremente_votes_pour' => 'sujets#incremente_votes_pour', as: :incremente_votes_pour
  patch '/sujets/:id/incremente_votes_contre' => 'sujets#incremente_votes_contre', as: :incremente_votes_contre
  patch '/sujets/:id/incremente_votes_blancs' => 'sujets#incremente_votes_blancs', as: :increase_votes_blancs

  get '/envoi_vote/:sujet/:vote' => 'sujets#envoi_vote'

  get 'sessions/new'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'utilisateurs#new', :as => 'sign_up'

  get 'groupes/:id/graphe' => 'groupes#graphe', :as => 'graphe'

  get 'admin' => 'admin#index'

  get '/accept/:id/:cle' => 'utilisateurs#verifier_mairie', as: :verifier_mairie

end

app/controllers/lieux_controller.rb
class LieuxController < ApplicationController
  before_action :require_admin

  def index
    @lieux = Lieu.all
  end

  def create
    @lieu = Lieu.new(lieux_params)
    @lieu.save
    redirect_to lieux_index_path
  end

  def destroy
    @lieu = Lieu.find_by_id(params[:id])
    @lieu.destroy
    redirect_to lieux_index_path
  end

  private
    def lieux_params
      params.require(:lieu).permit(
        :nom
      )
    end

end

app/helpers/lieux_helper.rb
module LieuxHelper

  def self.lieux_select
    Lieu.all.collect { |l| [l.nom, l.id] }
  end

end

app/views/lieux/index.html.erb
<h2>Modification des lieux</h2>
<p align="center">
<table>
  <thead>
    <tr>
      <td>
        Lieu
      </td>
      <td>
        Actions
      </td>
    </tr>
  </thead>
  <tbody>
    <% @lieux.each do |lieu| %>
      <tr>
        <td>
          <%= lieu.nom %>
        </td>
        <td>
          <%= link_to 'Supprimer', lieux_path(lieu), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>

<%= form_for :lieu do |f| %>
  <p>
  <%= f.label :nom, 'Nouveau lieu' %>
  </p>
  <p>
  <%= f.text_field :nom %>
  </p>
  <p>
  <%= f.submit 'Valider', class: 'btn-custom' %>
  </p>
<% end %>