config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  root 'pages#accueil'

  get '/accueil' => 'pages#accueil'
  get '/proposer'  => 'groupes#new'
  get '/mes_projets'  => 'groupes#index_mygroups'
  get '/voter' => 'groupes#index'
  get '/resultats' => 'groupes#index_outdated'
  get '/liste_utilisateurs' => 'utilisateurs#index'
  get '/a_propos' => 'pages#a_propos'

  resources :utilisateurs
  resources :delegations
  resources :sessions
  resources :groupes
  resources :lieux
  resources :categories
  resources :sujets do
    resources :commentaires
  end

  get '/ammendements/:id/new' => 'sujets#nouvel_ammendement', as: :nouvel_ammendement
  post '/ammendements' => 'sujets#creer_ammendement', as: :creer_ammendement

  patch '/sujets/:id/incremente_votes_pour' => 'sujets#incremente_votes_pour', as: :incremente_votes_pour
  patch '/sujets/:id/incremente_votes_contre' => 'sujets#incremente_votes_contre', as: :incremente_votes_contre
  patch '/sujets/:id/incremente_votes_blancs' => 'sujets#incremente_votes_blancs', as: :increase_votes_blancs

  get '/envoi_vote/:sujet/:vote' => 'sujets#envoi_vote'

  get 'sessions/new'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'utilisateurs#new', :as => 'sign_up'

  get 'groupes/:id/graphe' => 'groupes#graphe', :as => 'graphe'

  get 'admin' => 'admin#index'

  get '/accept/:id/:cle' => 'utilisateurs#verifier_mairie', as: :verifier_mairie

end

app/models/sujet.rb
# coding: utf-8
class Sujet < ActiveRecord::Base
  ####### ASSOCIATIONS ########
  belongs_to :createur,
             class_name: 'Utilisateur'

  belongs_to :parent,
             class_name: 'Sujet'

  belongs_to :groupe

  has_many :fils,
      class_name: 'Sujet',
      foreign_key: 'parent_id'

  has_and_belongs_to_many :utilisateurs,
                          class_name: 'Utilisateur',
                          join_table: 'votes'

  has_many :commentaires

  alias_method :votants, :utilisateurs

  ####### VALIDATION ######
  validates :createur, :groupe, :titre, :description,
            :votes_blancs, :votes_contre, :votes_pour, presence: true

  after_destroy :detruit_si_groupe_vide

  ###### FONCTIONS ######
  def nombre_votants
    tab_votes = resultat_votes[:pour] + resultat_votes[:contre] + resultat_votes[:blancs]
  end

  def resultat_votes
    url = 'http://localhost:3001/votes/' + self.id.to_s + '.json'
    response = HTTParty.get(url)

    v_pour = response.parsed_response['votes_pour']
    v_contre = response.parsed_response['votes_contre']
    v_blancs = response.parsed_response['votes_blancs']

    tab_votes = {pour: v_pour,
      contre: v_contre,
      blancs: v_blancs}
  end

  def votes(type_vote)
    tab_votes = resultat_votes
    tab_votes[type_vote]
  end

  def self.en_cours
    where(groupe_id: Groupe.en_cours.ids)
  end

  def emotion(texte)

    texteEnglish = HTTParty.post("http://www.frengly.com/",
    :query => { "src" => "fr",
                "dest" => "en",
                "text" => texte,
                "email" => "bara.julien@yahoo.fr",
                "password" => Rails.application.secrets.mot_de_passe_gmail})
    begin

    response = HTTParty.post("http://gateway-a.watsonplatform.net/calls/text/TextGetEmotion",
    :query => { "apikey" => "b76a130b969313ddf8daeac0cce33f44757579ee",
                "text" => texteEnglish["root"]["translation"],
                "outputMode" => "json"},
    :headers => { "Content-Type" => "application/x-www-form-urlencoded"})

      if response["status"] != "ERROR"
        retour = Array.new
        retour<<response["docEmotions"]["anger"]
        retour<<response["docEmotions"]["disgust"]
        retour<<response["docEmotions"]["fear"]
        retour<<response["docEmotions"]["joy"]
        retour<<response["docEmotions"]["sadness"]

        retour
      else
        "ERROR"
      end

    rescue
      puts "Error #{$!}"
    end

    retour = Array.new

    retour<<response["docEmotions"]["anger"]
    retour<<response["docEmotions"]["disgust"]
    retour<<response["docEmotions"]["fear"]
    retour<<response["docEmotions"]["joy"]
    retour<<response["docEmotions"]["sadness"]

    retour

  end

  def description_courte
    #sélectionne les 10 premiers mots de la chaine
    s = description.split[0, 15]
    desc = description.split[0,15].join(" ")
    if description.length > 150
      desc << "..."
    end
    desc
  end

  def victoire?
    (resultat_votes[:pour] > resultat_votes[:contre])
  end


  def resultat_phrase
    "Ce référendum a rassemblé " + votes_pour.to_s + " votes pour, " + votes_contre.to_s + " votes contre, " + votes_blancs.to_s + " votes blancs. "
  end

  def self.search(search)
    where{(titre.like "%#{search}%")|(description.like "%#{search}%")}
  end

  private
    def detruit_si_groupe_vide
      if !self.groupe.nil? && self.groupe.sujets.empty?
        self.groupe.destroy
      end
    end

end

app/controllers/sujets_controller.rb
# coding: utf-8
class SujetsController < ApplicationController
  before_action :require_login, except: :show
  before_action :require_admin, only: :destroy

  def show
    @sujet = Sujet.find_by_id(params[:id])
    if @sujet.nil?
      redirect_to root_path
    end

    @modulus = ""
    @exponent = ""
    File.open('cle_publique_serveur', "r") do |f|
      @exponent = f.readline(' ')
      @modulus = f.readline('')
    end
    @exponent = @exponent[0, @exponent.length-1]

    commentaires = ""

    @sujet.commentaires.each do |com|
      commentaires = commentaires + com.texte + " "
    end

    if commentaires != ""
      retour = @sujet.emotion(commentaires)
    else
      retour = "ERROR"
    end

    if retour != "ERROR"
      @Colere = retour[0]
      @Degout = retour[1]
      @Peur = retour[2]
      @Joie = retour[3]
      @Tristesse = retour[4]
    else
      @Colere = "ERROR"
      @Degout = "ERROR"
      @Peur = "ERROR"
      @Joie = "ERROR"
      @Tristesse = "ERROR"
    end
  end

  def new
    @sujet = Sujet.new
    @sujet_parent = Sujet.find_by_id(params[:parent_id])
    if @sujet_parent.nil?
      redirect_to groupes_url, notice: 'Sujet parent non-existant'
    end
  end

  def create
    @sujet = Sujet.new(sujet_params)
    @sujet_parent = Sujet.find_by_id(@sujet.parent_id)

    if @sujet_parent.nil?
      redirect_to groupes_url, notice: 'Sujet parent non-existant'
    else
      @sujet.groupe_id = @sujet_parent.groupe_id

      if @sujet.save
        redirect_to @sujet, notice: 'Le sujet a été créé.'
      else
        render 'new'
      end
    end
  end

  def destroy
    @sujet = Sujet.find_by_id(params[:id])
    if @sujet.nil?
      redirect_to :groupes
    else
      @sujet.destroy
      redirect_to @sujet.groupe, notice: 'Sujet supprimé'
    end
  end

  def envoi_vote
    paquet = params[:vote]
    @sujet = Sujet.find_by_id(params[:sujet])
    if @sujet.nil?
      redirect_to root_path
    else
      cat_id = @sujet.groupe.categorie_principale_id
      nb_votes = utilisateur_courant.votes_disponibles(cat_id)

      nb_votes.times {
        url = "http://localhost:3001/votes/" + @sujet.id.to_s + "/" + paquet.to_s
        response = HTTParty.get(url)
      }

      # 5.times do
      #   # attente = Attente.new(vote: paquet, sujet: @sujet.id)
      #   # attente.save
      # end

      @sujet.votants.append(utilisateur_courant.delegueurs_et_moi(cat_id))
      redirect_to @sujet
    end
  end

  def incremente_votes_pour
    incremente_votes(:votes_pour)
  end

  def incremente_votes_contre
    incremente_votes(:votes_contre)
  end

  def incremente_votes_blancs
    incremente_votes(:votes_blancs)
  end

  private
    def incremente_votes(type_vote)
      @sujet = Sujet.find_by_id(params[:id])
      if @sujet.nil?
        redirect_to root_path
      else
        cat_id = @sujet.groupe.categorie_principale_id
        @sujet.update_attributes(type_vote => @sujet[type_vote] +
            utilisateur_courant.votes_disponibles(cat_id))
        @sujet.votants.append(utilisateur_courant.delegueurs_et_moi(cat_id))
        render 'show'
      end
    end

    def sujet_params
      params.require(:sujet).permit(:titre, :description, :parent_id).merge(
            votes_blancs: 0, votes_pour: 0, votes_contre: 0, createur_id: utilisateur_courant.id
      )
    end

    def attente_params
      params.require(:attente).permit(
          :vote,
          :sujet
      )
    end

end

app/helpers/sujets_helper.rb
module SujetsHelper

end

app/views/sujets/_sujet.html.erb
<div class="well">

  <h4><%= link_to sujet.titre, sujet %></h4>

  <div class="pull-right text-right">
    <span style="font-size: 120%;"><%= pluralize(sujet.nombre_votants, 'vote') %></span>
  </div>

  <p>
    <%= sujet.description_courte %>
  </p>

  <% if sujet.fils.length > 0 %>
    <div>
      Amendements de ce groupe :
      <ul>
        <% sujet.fils.each do |s| %>
          <li><%= link_to s.titre, s %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/sujets/_vote_en_cours.html.erb
<div>
  <% if @sujet.utilisateurs.exists?(utilisateur_courant) %>

    <div class="text center">
      Vous avez déjà voté pour ce référendum.
    </div>

  <% else %>

    <div class="text-center">
      <% if logged_in? %>

      <input value="Vote pour" type="button" id="vote_pour">
      <input value="Vote contre" type="button" id="vote_contre">
      <input value="Vote blanc" type="button" id="vote_blanc">

      <% else %>
        Vous devez être connecté pour pouvoir voter.
      <% end %>

    </div>

    <script type="text/javascript">
      $("#vote_pour").click(function(){
        envoi_votes(<%= @sujet.id %>, "<%= @modulus %>", "<%= @exponent %>", 1);
      });
      $("#vote_contre").click(function(){
        envoi_votes(<%= @sujet.id %>, "<%= @modulus %>", "<%= @exponent %>", 2);
      });
      $("#vote_blanc").click(function(){
        envoi_votes(<%= @sujet.id %>, "<%= @modulus %>", "<%= @exponent %>", 3);
      });
    </script>

  <% end %>

  <div>
    <div class="bg-info clearfix" style="padding: 15px;">
      Vous pouvez également proposer un amendement à cette idée. Un amendement est une modification de l'idée actuelle, qui vous semble mieux adaptée pour répondre au problème. L'amendement aura son propre vote et son propre fil de commentaire, et se terminera en même temps que le groupe auquel il est associé.
      <div class="pull-right" style="margin: 10px;">
        <%= link_to 'Créer un amendement', { action: :new, parent_id: @sujet.id }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>

</div>

app/views/sujets/_vote_termine.html.erb
<div>
  <p>
    <h3>Résultats</h3>

    <p style="font-size: 200%;">
      <% if @sujet.resultat_votes[:pour] > @sujet.resultat_votes[:contre] %>
        La communauté a voté pour !
      <% elsif @sujet.resultat_votes[:pour] < @sujet.resultat_votes[:contre] %>
        La communauté a voté contre.
      <% elsif @sujet.resultat_votes[:pour] == @sujet.resultat_votes[:contre] %>
        Le vote a obtenu une égalité.
      <% end %>
    </p>

    <ul>
      <li><%= @sujet.resultat_votes[:pour] %> utilisateurs ont voté pour.</li>
      <li><%= @sujet.resultat_votes[:contre] %> utilisateurs ont voté contre.</li>
      <li><%= @sujet.resultat_votes[:blancs] %> utilisateurs ont voté blanc.</li>
    </ul>

  </p>
</div>

app/views/sujets/new.html.erb
<div class="row">
  <div class="col-sm-2 vcenter">
    <%= link_to 'Retour au sujet', sujet_path(@sujet_parent), class: 'btn btn-default btn-sm' %>
  </div>
  <div class="col-sm-8 text-center vcenter">
    <h1>Nouvel amendement pour le sujet <%= link_to @sujet_parent.titre, sujet_path(@sujet_parent) %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= form_for @sujet do |f| %>
      <%= render 'layouts/erreurs', erreurs: @sujet.errors %>

      <div class="form-group">
        <%= f.label :titre %>
        <%= f.text_field :titre, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <%= f.hidden_field :parent_id, value: @sujet_parent.id %>

      <%= f.submit 'Publier', class: 'btn btn-primary btn-lg' %>
    <% end %>
  </div>
</div>

app/views/sujets/show.html.erb
<div class="row">
  <div class="col-sm-2 vcenter">
    <%= link_to 'Retour à l\'idéospère', groupe_path(@sujet.groupe_id), class: 'btn btn-default btn-sm' %>
  </div>
  <div class="col-sm-8 text-center vcenter">
    <h1><%= @sujet.titre %></h1>
  </div>
</div>

<% unless notice.nil? %>
  <p id="notice text-center"><%= notice %></p>
<% end %>

<% unless @sujet.parent.nil? %>
  <p class="bg-info" style="padding: 15px;">
    Ce référendum est un amendement du référendum <%= link_to @sujet.parent.titre, sujet_path(@sujet.parent) %> proposé par <%= link_to @sujet.parent.createur.nom_complet, utilisateur_path(@sujet.parent.createur) %>.
  </p>
<% end %>

<div class="row">
  <div class="col-lg-6">

    <div>
      <h2>Description</h2>
      <p>
        <%= @sujet.description %>
      </p>
    </div>

    <div>
      <h2>Informations</h2>

      <p>
        Proposé par <strong><%= link_to @sujet.createur.nom_complet, utilisateur_path(@sujet.createur) %></strong> le <strong><%= l @sujet.created_at, format: :long %></strong>.
      </p>

      <p>
        <strong><%= @sujet.nombre_votants %></strong> personnes ont voté sur ce sujet.
      </p>

      <h2>Progression du vote</h2>

      <div>

        <p>Ouverture : <strong><%= l @sujet.groupe.date_debut, format: :long %></strong></p>
        <p>Fermeture : <strong><%= l @sujet.groupe.date_fin, format: :long %></strong></p>
        <p>Temps restant : <strong><%= @sujet.groupe.temps_restant_str %></strong></p>

        <div>
          <div class="progress">
            <div class="progress-bar" style="width:<%= @sujet.groupe.pourcentage_restant %>%">
            </div>
          </div>
        </div>

      </div>

    </div>

    <% if @sujet.groupe.termine? %>
      <%= render 'vote_termine' %>
    <% else %>
      <%= render 'vote_en_cours' %>
    <% end %>

  </div>

  <div class="col-lg-6">

    <h2>Commentaires</h2>

    <% @sujet.commentaires.each do |commentaire| %>
      <%= render(commentaire) %>
    <% end %>

    <% if logged_in? %>
      <h3>Ajouter un commentaire</h3>

      <%= form_for([@sujet, @sujet.commentaires.build]) do |f| %>
        <%= f.text_area :texte, placeholder: 'Votre commentaire...', class: 'form-control' %>
        <%= f.submit 'Écrire un commentaire', class: 'btn btn-default' %>
      <% end %>

    <% else %>
      <p>Vous devez être connecté(e) pour publier un commentaire. </p>
    <% end %>

    <h2>Sentiment des commentaires</h2>

    <% if @Colere != "ERROR" %>

      <div class="row">
        <div class="col-lg-2">
          <strong>Colère</strong>
        </div>
        <div class="col-lg-2">
          <%= (@Colere.to_f*1000).to_i.to_f/10 %>%
        </div>
        <div class="col-lg-8">
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= @Colere.to_f*100 %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @Colere.to_f*100 %>%; background: #c82222">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-2">
          <strong>Dégoût</strong>
        </div>
        <div class="col-lg-2">
          <%= (@Degout.to_f*1000).to_i.to_f/10 %>%
        </div>
        <div class="col-lg-8">
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= @Degout.to_f*100 %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @Degout.to_f*100 %>%; background-color: #194923">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-2">
          <strong>Peur</strong>
        </div>
        <div class="col-lg-2">
          <%= (@Peur.to_f*1000).to_i.to_f/10 %>%
        </div>
        <div class="col-lg-8">
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= @Peur.to_f*100 %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @Peur.to_f*100 %>%; background-color: #723183">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-2">
          <strong>Joie</strong>
        </div>
        <div class="col-lg-2">
          <%= (@Joie.to_f*1000).to_i.to_f/10 %>%
        </div>
        <div class="col-lg-8">
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= @Joie.to_f*100 %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @Joie.to_f*100 %>%; background-color: #f1a013">
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-2">
          <strong>Tristesse</strong>
        </div>
        <div class="col-lg-2">
          <%= (@Tristesse.to_f*1000).to_i.to_f/10 %>%
        </div>
        <div class="col-lg-8">
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="<%= @Tristesse.to_f*100 %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @Tristesse.to_f*100 %>%; background-color: #303e89">
            </div>
          </div>
        </div>
      </div>

    <% end %>

  </div>
</div>