config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  root 'pages#accueil'

  get '/accueil' => 'pages#accueil'
  get '/proposer'  => 'groupes#new'
  get '/mes_projets'  => 'groupes#index_mygroups'
  get '/voter' => 'groupes#index'
  get '/resultats' => 'groupes#index_outdated'
  get '/liste_utilisateurs' => 'utilisateurs#index'
  get '/a_propos' => 'pages#a_propos'

  resources :utilisateurs
  resources :delegations
  resources :sessions
  resources :groupes
  resources :lieux
  resources :categories
  resources :sujets do
    resources :commentaires
  end

  get '/ammendements/:id/new' => 'sujets#nouvel_ammendement', as: :nouvel_ammendement
  post '/ammendements' => 'sujets#creer_ammendement', as: :creer_ammendement

  patch '/sujets/:id/incremente_votes_pour' => 'sujets#incremente_votes_pour', as: :incremente_votes_pour
  patch '/sujets/:id/incremente_votes_contre' => 'sujets#incremente_votes_contre', as: :incremente_votes_contre
  patch '/sujets/:id/incremente_votes_blancs' => 'sujets#incremente_votes_blancs', as: :increase_votes_blancs

  get '/envoi_vote/:sujet/:vote' => 'sujets#envoi_vote'

  get 'sessions/new'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'utilisateurs#new', :as => 'sign_up'

  get 'groupes/:id/graphe' => 'groupes#graphe', :as => 'graphe'

  get 'admin' => 'admin#index'

  get '/accept/:id/:cle' => 'utilisateurs#verifier_mairie', as: :verifier_mairie

end

app/models/groupe.rb
class Groupe < ActiveRecord::Base
  has_many :sujets, :dependent => :delete_all

  belongs_to :categorie_principale,
             class_name: 'Categorie'
  belongs_to :categorie_secondaire,
             class_name: 'Categorie'
  belongs_to :lieu

  # Recherche de tous les groupes dont les sujets ou les catégories sont en rapport
  def self.search(search)
    categories_ids = Categorie.search(search).ids
    where{(id.in(Sujet.search(search).select{groupe_id})) |
        (categorie_principale_id.in(categories_ids)) |
        (categorie_secondaire_id.in(categories_ids))}
  end

  def votes_total
    self.sujets.inject(0) do |total, sujet|
      total + sujet.nombre_votants
    end
  end

  def createur
    self.sujets.first.createur
  end

  def en_cours?
    DateTime.now.between? self.date_debut, self.date_fin
  end

  def self.en_cours
    where{(date_debut <= DateTime.now) & (date_fin >= DateTime.now)}
  end

  def pourcentage_restant
    termine = date_fin - date_debut
    en_cours = (Time.current - date_debut)
    pourcentage = 100 - ((en_cours * 100) / termine).to_i
    if pourcentage > 100
      pourcentage = 100
    elsif pourcentage < 0
      pourcentage = 0
    end
    pourcentage
  end

  def temps_restant
    if termine?
      {jours: 0, heures: 0, minutes: 0}
    else
      t = (date_fin - Time.current).to_i
      mm, ss = t.divmod(60)
      hh, mm = mm.divmod(60)
      dd, hh = hh.divmod(24)
      {jours: dd, heures: hh, minutes: mm}
    end
  end

  def temps_restant_str
    "%d jours, %d heures, %d minutes" % [temps_restant[:jours], temps_restant[:heures], temps_restant[:minutes]]
  end

  def termine?
    date_fin < Time.current
  end

  def description_courte
    self.sujets.first.description_courte
  end

  def victoire?
    self.sujets.first.victoire?
  end

end

app/controllers/groupes_controller.rb
# coding: utf-8
class GroupesController < ApplicationController

  before_action :require_login, only: [:new, :edit, :create]
  before_action :require_admin, only: :destroy

  respond_to :html, :json

  # GET /groupes
  def index
    if params[:search]
      @groupes = Groupe.search(params[:search]).order(created_at: :desc)
    else
      @groupes = Groupe.order(created_at: :desc)
    end
    @groupes = @groupes.select { |g| !g.termine? }
    @groupes_pelos, @groupes_institutionnels = @groupes.partition { |g| g.createur.pelo? }
  end

  def index_outdated
    if params[:search]
      @groupes = Groupe.search(params[:search]).order(created_at: :desc)
    else
      @groupes = Groupe.order(created_at: :desc)
    end
    @groupes = @groupes.select { |g| g.termine? }
    @groupes_pelos, @groupes_institutionnels = @groupes.partition { |g| g.createur.pelo? }
  end

  def index_mygroups
    if params[:search]
      @groupes = Groupe.search(params[:search]).order(created_at: :desc)
    else
      @groupes = Groupe.order(created_at: :desc)
    end
    @groupes = @groupes.select { |g| g.createur == utilisateur_courant }
    @termines, @en_cours = @groupes.partition { |g| g.termine? }
  end

  # A SUPPRIMER SI TOUT MARCHE
  #alias_method :index_outdated, :index
  #alias_method :index_mygroups, :index

  # GET /groupes/1
  def show
    @groupe = Groupe.find_by_id(params[:id])
  end

  # GET /groupes/new
  def new
    @groupe = Groupe.new
    @sujet = Sujet.new
    # redirect_to controller: sujets_url, action: new #, :titre => titre
    # redirect_to use_route: 'sujets/new'
  end

  # GET /groupes/1/edit
  def edit
  end

  # POST /groupes
  def create
    @groupe = Groupe.new(groupe_params)
    if @groupe.save
      @sujet = Sujet.new(sujet_params)
      @sujet.createur = utilisateur_courant
      @sujet.votes_pour = 0
      @sujet.votes_blancs = 0
      @sujet.votes_contre = 0
      @sujet.groupe = @groupe
      @sujet.titre = @groupe.titre
      if @sujet.save
        redirect_to @groupe, notice: 'Groupe was successfully created.'
      else
        @groupe.destroy
        render :new
      end
    else
      render :new
    end
  end

  def destroy
    groupe = Groupe.find_by_id(params[:id])
    unless groupe.nil?
      groupe.destroy
    end
    redirect_to :groupes
  end

  def graphe
    @groupe = Groupe.find(params[:id])
    respond_to do |format|
      format.json {

        nodes = @groupe.sujets
        links = nodes.select {|node| !node.parent.nil?}.collect do |node|
          {
            source: nodes.index(node),
            target: nodes.index(node.parent)
          }
        end

        render json: {
            nodes: nodes,
            links: links
          }
      }
    end
  end

  private
    def groupe_params
      params.require(:groupe).permit(:titre,
        :date_debut,
        :date_fin,
        :categorie_principale_id,
        :categorie_secondaire_id)
    end

    def sujet_params
      params.require(:sujet).permit(:description)
    end

end

app/helpers/groupes_helper.rb
module GroupesHelper
end

app/views/groupes/_groupe.html.erb
<div class="well">

  <h4><%= link_to groupe.titre, groupe %></h4>

  <div class="pull-right text-right">
    <span style="font-size: 120%;"><%= pluralize(groupe.votes_total, 'vote') %></span><br>
    Terminé le <strong><%= l groupe.date_fin, format: :short %></strong>
  </div>

  <p>
    <%= groupe.description_courte %>
  </p>
  <div>
    Référendums de ce groupe :
    <ul>
      <% groupe.sujets.each do |s| %>
        <li>
          <%= link_to s.titre, s %>
          <% if groupe.termine? %>
            (<span style="color: green;"><%= s.resultat_votes[:pour] %>+</span>, <%= s.resultat_votes[:blancs] %>~, <span style="color: red;"><%= s.resultat_votes[:contre] %>-</span>)
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/groupes/index.html.erb
<% unless notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Projets ouverts au vote</h1>
    <div class="text-center">
      <%= form_tag(voter_path, method: 'get', id: 'search-form', class: 'form-inline') do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: 'Recherche...', class: 'form-control' %>
            <%= submit_tag 'Rechercher', class: 'btn btn-default' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 text-center">
    <% if logged_in? %>
      <%= link_to 'Proposer un nouveau projet', proposer_path, class: 'btn btn-primary btn-lg' %>
    <% else %>
      <%= link_to 'Connectez vous pour proposer un projet', log_in_path, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<!-- Liste des référendums -->
<div class="row">

  <div class="col-lg-6">
    <h3>Projets institutionnels</h3>
    <% @groupes_institutionnels.each do |groupe| %>
      <%= render groupe %>
    <% end %>
  </div>


  <div class="col-lg-6">
    <h3>Projets citoyens</h3>
    <% @groupes_pelos.each do |groupe| %>
      <% render groupe %>
    <% end %>
  </div>

</div>

app/views/groupes/index_mygroups.html.erb
<% unless notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>

<h1 class="text-center">Mes projets</h1>

<div class="row">
  <div class="col-lg-12 text-center">
    <%= form_tag(voter_path, :method => "get", id: "search-form", class: 'form-inline') do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Recherche...', class: 'form-control' %>
      <%= submit_tag 'Rechercher', class: 'btn btn-default' %></p>
    <% end %>
    <%= link_to 'Proposer un nouveau projet', proposer_path, class: 'btn btn-primary' %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">

    <h2>Projets en cours</h2>

    <table class="table table-hover">

      <thead>
        <tr>
          <th>Projet</th>
          <th>Nombre de Votants</th>
          <th>Ouverture</th>
          <th>Fermeture</th>
        </tr>
      </thead>

      <tbody>
        <% @en_cours.each do |groupe| %>
          <tr onclick="location.href='<%= groupe_path groupe %>';">
            <td><%= link_to groupe.titre, groupe %></td>
            <td><%= groupe.votes_total %></td>
            <td><%= l groupe.date_debut, format: :long %></td>
            <td><%= l groupe.date_fin, format: :long %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-md-6">
    <h2>Projets terminés</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Projet</th>
          <th>Nombre de votants</th>
          <th>Fermeture</th>
          <th>Résultat</th>
        </tr>
      </thead>

      <tbody>
        <% @termines.each do |groupe| %>
          <tr onclick="location.href='<%= groupe_path groupe %>';">
            <td><%= link_to groupe.titre, groupe %></td>
            <td><%= groupe.votes_total %></td>
            <td><%= l groupe.date_fin, format: :long %></td>
            <td>
              <% if groupe.victoire? %>
                <span style="color: green;">Accepté</span>
              <% else %>
                <span style="color: red;">Rejeté</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/groupes/index_outdated.html.erb
<% unless notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Projets terminés</h1>
    <div>
      <%= form_tag(resultats_path, method: 'get', id: 'search-form', class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: 'Recherche...', class: 'form-control' %>
          <%= submit_tag 'Rechercher', class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Liste des référendums -->
<div class="row">

  <div class="col-lg-6">

    <h3>Projets institutionnels</h3>

    <% @groupes_institutionnels.each do |groupe| %>
      <%= render groupe %>
    <% end %>

  </div>

  <div class="col-lg-6">

    <h3>Projets citoyens</h3>

    <% @groupes_pelos.each do |groupe| %>
      <%= render groupe %>
    <% end %>

  </div>

</div>

app/views/groupes/new.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h2>Créer un nouveau projet</h2>
  </div>
</div>

<% unless @groupe.errors.empty? && @sujet.errors.empty? %>
  <div class="row">
    <div class="col-lg-12">
      <%= render 'layouts/erreurs', erreurs: @groupe.errors%>
      <%= render 'layouts/erreurs', erreurs: @sujet.errors%>
    </div>
  </div>
<% end %>

<%= form_for(@groupe) do |f| %>

  <div class="form-group">
    <%= f.label :titre %>
    <%= f.text_field :titre, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label :sujet, :description %>
    <%= text_area :sujet, :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :categorie_principale_id, 'Catégorie principale' %>
    <%= f.select :categorie_principale_id, Categorie.all.pluck(:nom, :id), {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= f.label :categorie_secondaire_id, 'Catégorie secondaire (optionnelle)' %>
    <%= f.select :categorie_secondaire_id, [['Aucune', nil]] + Categorie.all.pluck(:nom, :id), {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date_debut, 'Date de début' %><br>
    <%= f.datetime_select :date_debut,
      use_two_digit_numbers: true,
      date_separator: ' / ',
      start_year: Date.today.year,
      default: Time.now
    %>
  </div>

  <div class="form-group">
    <%= f.label :date_fin, 'Date de fin' %><br>
    <%= f.datetime_select :date_fin,
      use_two_digit_numbers: true,
      date_separator: ' / ',
      start_year: Date.today.year,
      default: 7.days.from_now
    %>
  </div>

  <%= f.submit 'Publier', class: 'btn btn-primary btn-lg' %>

<% end %>

app/views/groupes/show.html.erb
<% unless notice.nil? %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-lg-12 text-center">
    <h1><%= @groupe.titre %></h1>
  </div>
</div>

<div class="row">

  <div class="col-md-6">

    <h2>Informations</h2>

    <div>

      <dl>
        <dt>Catégorie principale</dt>
        <dd><%= @groupe.categorie_principale.nom %></dd>

        <dt>Catégorie secondaire</dt>
        <dd>
          <% if @groupe.categorie_secondaire.nil? %>
            <i>Aucune</i>
          <% else %>
            <%= @groupe.categorie_secondaire.nom %>
          <% end %>
        </dd>

        <dt>Vote ouvert jusqu'au</dt>
        <dd><%= @groupe.date_fin.strftime("%d/%m/%Y à %Hh%M") %></dd>
      </dl>

      <p style="font-size: 150%;">
        <% if @groupe.termine? %>
          Vote terminé !
        <% else %>
          Il reste <%= @groupe.temps_restant_str %> avant la fin du vote.
        <% end %>
      </p>

    </div>

    <% @groupe.sujets.each do |sujet| %>
      <%= render sujet %>
    <% end %>

  </div>

  <div class="col-lg-6 text-center">
    <h2>Idéosphère</h2>

    <% if @groupe.sujets.length > 1 %>
      <div id="graphe">
      </div>
      <script type="text/javascript">
        graphe("#graphe");
      </script>
    <% else %>
      Désolé ! Il faut au moins un amendement pour voir l'idéosphère.
    <% end %>
  </div>

</div>

<div class="row">
  <div class="col-lg-12 text-center">
    <%= link_to 'Retour à la liste des projets', groupes_path, class: 'btn btn-default' %>
  </div>
</div>